### ISSUE TITLE
Criticas Construtivas! 

### ISSUE THREAD

**Issue by JhoanDev** [classroom-ufersa/buscaPorInterpolacaoClientes#1]
O código está otimo!

porém tenho alguns pontos a destacar.

1# Utilizar mais de uma branch para não haver commits direto na main, sugiro utilização de git flow, vou anexar o link : [sobre o git flow](https://www.atlassian.com/br/git/tutorials/comparing-workflows/gitflow-workflow)

2# poderiam também padronizar os nomes na lida e na busca 
ex: eu digitar peDrO e mesmo assim achar o Pedro.

**Comment by JhoanDev** [comment]
@DuardoEdu2 @gusjjpv @marceloDev0 @ViniciusOliver13

**Comment by marceloDev0** [comment]
bom dia jhoan, fizemos a tratativa de erro do segundo ponto comentado você poderia verifica-la por favor?  Obrigado pelo comentário sentisse a vontade para fazer novas issues. @JhoanDev
